@echo off
setlocal enabledelayedexpansion
title WinRevive - Fix Internet

echo Resetting TCP/IP stack...
netsh int ip reset >nul
echo Flushing DNS cache...
ipconfig /flushdns
echo Resetting Winsock catalog...
netsh winsock reset >nul
echo Releasing IP address...
ipconfig /release >nul
echo Renewing IP address...
ipconfig /renew >nul
echo Disabling proxy settings...
reg delete "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings" /v ProxyEnable /f >nul 2>&1
echo Internet stack repaired. A restart may be required.
endlocal
